AospExtended/official_devices

devices.json

signed-off by: Amol Amrit<amol.amrit99@gmail.com>

Update devices.json: Add Redmi Note 3 Maintainer

---

devices.json

Add OnePlus 3/3T

---

devices.json

Update for surnia (#2)

---

devices.json

REMOVE TITAN THEN I HAVE NO TITAN MORE

REMOVE TITAN

---

devices.json

I hope it's not a problem for your script to have 2 devices with the same name (different variants of the same device)

Added device D801

---

devices.json

*Removed the duplicate which was showing LG LG G2.

Corrected Name Of LG G2

---

devices.json

*Added Galaxy Grand Prime Variants To The Extended Family.

Galaxy Grand Prime Bringup

---

devices.json

Signed-off-by: mohancm100 <mohanmanjappa@gmail.com>

Add Lenovo Vibe K4 Note(A7010a48)

---

devices.json

All The Builds For Different Variants Were In A Single Folder Which Is Kind Of Messed Up.
Separating The Builds Into Different Folders Is Better.

Grand Prime: Seperate Download Folders.

---

devices.json

Added Androıd one 2rd Devıce

---

devices.json

Signed-off-by: mohancm100 <mohanmanjappa@gmail.com>

Add Coolpad Note 3(CP8676_I02)

---

devices.json

Nexus 6 shamu

---

devices.json

Devices: Add LeEco Le Pro 3 (zl1)

---

devices.json

Add Bq Aquaris X5 Plus
Edit mantainer Allurba to Albert Llurba (allurba)

Add Bq Aquaris X5 Plus and edit mantainer

---

devices.json

Added K3 Note support (aio_otfp)

Added K3 Note

---

devices.json

This is my first device I maintenanced.

Add Mi-4c(libra)

---

devices.json

Add Nexus 5X to official AospExtended devices

Extending Nexus 5X

---

devices.json

add ZUK Z2 plus

---

devices.json

devices: Update List (Ft. Farewell Subham Padhi)

---

devices.json

Signed-off-by: Gianmarco Scarano <gianmarcoscarano@gmail.com>

Update Moto G4 Plus

---

devices.json

Sexy Derp!

---

devices.json

Official Bucket: Add Redmi 3s/Prime (land)

---

devices.json

Update all Redmi4X info,darshan left.Thanks

Update Redmi4X Info

---

devices.json

Thread has been moved to original android development now.

Update thread location of Z00T

---

devices.json

*Extend the description of G530H variants and add G530W-T-T1 variants to Official list.

devices: Grand Prime: Add G530W-T-T1 variants

---

devices.json

Sorry guys... I changed of device.

devices: Kill The Moto X 2014 && Moto E

---

changelog/ham/20180114-1726.txt
devices.json

Change-Id: I92726a73ee14dd43744dce04ff65517fd39765ae
Signed-off-by: ShubhamB6596 <shubhamprince111@gmail.com>

Add Zuk Z1

---

devices.json

Signed-off-by: harry8242 <mohamedharis97@gmail.com>

Devices: Add Lenovo Vibe K5/K5 Plus(A6020)

---

devices.json

add yureka

---

devices.json

devices: Add co-maintainer for A6020

---

devices.json

Change-Id: I13d18a084541d916e27d744a05c89d61bfab69cf

Add Yu Yuphoria (Lettuce)

---

changelog/lettuce/20180208-1643.txt

Change-Id: Iaa08a1d5f647100c16907eaac91311e4ad669a1a

Lettuce: Add changelog for 8th feb build

---

devices.json

devices: Kill MI 6&Add Redmi Note5/Redmi 5 Plus

---

devices.json

I am Still Alive work starting soon -Amy

Add Nexus 6P

---

changelog/oneplus2/20180303-1456.txt

Signed-off-by: Jagrav Naik <jagravnaik0@gmail.com>

AEX 5.2 for oneplus2

---

changelog/santoni/20180316-0042.txt
devices.json

Add Santoni 20180316 0042 Release

---

changelog/santoni/20180406-0531.txt

santoni: v5.4

---

changelog/santoni/20180406-1214.txt

santoni: 20180406 1214

---

changelog/scorpio/20180414-1208.txt
devices.json

* starting with 20180414-1208 build

Add Mi Note 2 aka scorpio

---

changelog/santoni/20180414-1402.txt

santoni: 20180414-1402

---

changelog/condor/changelog.txt

Add condor to the changelog folder

add condor

---

changelog/santoni/20180420-1621.txt

Signed-off-by: Isaac Chen <tingyi364@gmail.com>

santoni: 20180420-1621

---

devices.json

Update surnia's XDA thread link

---

devices.json

Signed-off-by: Akash Mondal <a98mondal@gmail.com>

Device: Updated maintainer of s2

---

devices.json

Signed-off-by: SVR-RKM <srinivasarajumaharaj@gmail.com>

Add Asus Zenfone3 (Libra )

---

devices.json

harpia: drop maintainer

---

devices.json

Change-Id: Ib4bbc8056ced7ea26f1b4b46943dc0f2954d7e3f

devices: say hi to srtphone

---

devices.json

AmulyaX added as the new maintainer for Xiaomi Redmi 5 Plus/Note 5 (vince)

vince: Update maintainer

---

devices.json

Add AospExtended v6.0 Pie for Xiaomi Redmi 5 Plus/Note 5 (vince)

vince: Add Pie support

---

devices.json

Add Xiaomi Mi 6 to Official

---

devices.json

- 4 Variants of Galaxy note 3: Hlte, Hltechn, Hltekor, Hltetmo

Add Samsung Galaxy Note 3 LTE to Official.

---

devices.json

Signed-off-by: SagarMakhar <sagarmakhar@gmail.com>

devices: add pie support for X00TD

---

devices.json

Signed-off-by: fatesay <dmf040619@163.com>

add official device cancro

---

devices.json

Hi, PLEASE CLOSE OTHER REDMI 5 ITS WRONG!!!
Contact me on telegram: @AndroidPie9

Add redmi 5 rosy (please CLOSE other its wrong)

---

devices.json

* Always Late but worth the Wait.

official_devices: Pie for whyred

---

devices.json

Edited too the name of Devices (Redmi 4A/5A) now.

official_devices: Pie for rolex/riva

---

devices.json

device: Add jasmine

---

devices.json

devices: Remove extra comma ;-;
